name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: 'Print JShell version (triggers creation of user preferences directory)'
      run: jshell --version
    - name: 'Build using JShell'
      run: jshell make-java.jsh
    - name: 'Build using local launcher'
      run: ./make-java
    - name: 'Set up JUnit'
      uses: sormuras/setup-junit@master
      id: junit
    - name: 'Compile and run all tests'
      run: |
        javac -d .make-java/classes --class-path ${{ steps.junit.outputs.standalone-jar }}:.make-java/classes $(find src/test -name "*.java")
        java -jar ${{ steps.junit.outputs.standalone-jar }} --class-path .make-java/classes --scan-class-path
